import { User, Product, Order } from './types';

// Raw Data
const RAW_USERS = [
  {"code": "CEA-001", "name": "AROMATICA TUY."},
  {"code": "CEA-004", "name": "INVERSIONES CEPORT. C.A."},
  {"code": "CEA-005", "name": "NOVEDADES Y PUNTO SANTA BARBARA. F.P"},
  {"code": "CEA-006", "name": "VARIEDADES HEYMAR. F.P"},
  {"code": "CEA-008", "name": "VILLA-BEL. C.A."},
  {"code": "CEA-009", "name": "PAOLA IMPORT COLECCIONS. C.A."},
  {"code": "CEA-010", "name": "COMERCIALIZADORA Y BODEGON YULUIS. C.A."},
  {"code": "CEA-011", "name": "INVERSIONES MARI'G 2017. F.P."},
  {"code": "CEA-012", "name": "INVERSIONES R.G BENDICIONES,C.A"},
  {"code": "CEA-013", "name": "INVERSIONES FRANCYBEL. C.A"},
  {"code": "CEA-014", "name": "NANCY SPA ESTETICA Y COSMETOLOGIA C.A"},
  {"code": "CEA-015", "name": "CENTRO DE BELLEZA Y ESTETICA VICTORYS"},
  {"code": "CEA-017", "name": "VARIEDADES DON FELIPE. C.A"},
  {"code": "CEA-018", "name": "INVERSIONES MAURERA 2018 F P.\n"},
  {"code": "CEA-019", "name": "INVERSIONES CHELYN. C.A"},
  {"code": "CEA-020", "name": "DISTRIBUIDORA MODA FASHIONS C.A."},
  {"code": "CEA-021", "name": "COMERCIALIZADORA CARLEORI. C.A"},
  {"code": "CEA-022", "name": "DILCE IRENE PEREZ DE COELLO"},
  {"code": "CEA-023", "name": "YORELIS DEL CARMEN DIAZ ABREU"},
  {"code": "CEA-024", "name": "EMPRESAS LABYS & ALBYS. C.A"},
  {"code": "CEA-026", "name": "ERDIS JOSEFINA BRITO"},
  {"code": "CEA-027", "name": "INVERSIONES Y VARIEDADES LYP. CA"},
  {"code": "CEA-028", "name": "NAYIVIS DEL CARMEN DOMINGUEZ DE MANZI"},
  {"code": "CEA-029", "name": "MARIA SOLEDAD PERALES"},
  {"code": "CEA-030", "name": "MARISOL GALAN"},
  {"code": "CEA-032", "name": "AURA MARILEX ORTIZ GIL"},
  {"code": "CEA-033", "name": "MARIANNY JOSE ALMAO PIÑA"},
  {"code": "CEA-034", "name": "MARIA ELENA NOGUEIRAS QUINTAS"},
  {"code": "CEA-035", "name": "CELSA GUILLERMINA UTRERA"},
  {"code": "CEA-036", "name": "PETRA HERNANDEZ HIDALGO"},
  {"code": "CEA-037", "name": "COMERCIALIZADORA SAY VIRGUEZ 2017. F.P."},
  {"code": "CEA-038", "name": "CARMEN CECILIA ASUAJE DE BASTIDAS"},
  {"code": "CEA-039", "name": "MARIA ISABEL LUGO DE TORRES"},
  {"code": "CEA-040", "name": "CARMEN JOSEFINA PEREZ DE SANCHEZ"},
  {"code": "CEA-041", "name": "BERTA KAIMIR RAMIREZ REYES"},
  {"code": "CEA-043", "name": "GLORIA MAGDALENA VARGAS"},
  {"code": "CEA-044", "name": "PAOLA IMPORT COLECCIONS. C.A. - FALCON"},
  {"code": "CEA-045", "name": "GLADYS CELINDA VARGAS ARTEAGA"},
  {"code": "CEA-046", "name": "JUANA BARTOLA GONZALEZ AREVALO"},
  {"code": "CEA-048", "name": "MARILU VIELMA RIVERA"},
  {"code": "CEA-049", "name": "BERNARDA ROSA FLORES DE OROZCO"},
  {"code": "CEA-051", "name": "ISARYS MARIBEL MIRANDA PAEZ"},
  {"code": "CEA-052", "name": "HORTENSIA JOSEFINA GODOY RAMIREZ"},
  {"code": "CEA-053", "name": "LIBIA JOSEFINA SOTO ROCHA"},
  {"code": "CEA-054", "name": "ORGA JOSEFINA TORREALBA DE MARRERO"},
  {"code": "CEA-055", "name": "INVERSIONES MARYLUIS. F.P"},
  {"code": "CEA-056", "name": "IBAN DARIO GONZALEZ MONCADA"},
  {"code": "CEA-057", "name": "ISNELIDA MARBELLA PACHECO"},
  {"code": "CEA-058", "name": "ALEIDA YUDITH CASTILLO"},
  {"code": "CEA-059", "name": "IRIS DEL CARMEN PERNALETE PEREZ"},
  {"code": "CEA-061", "name": "MARIELBA RICARDI DE HERNANDEZ"},
  {"code": "CEA-062", "name": "DILENIA DEL VALLE MARTINEZ VIÑOLES"},
  {"code": "CEA-063", "name": "LUISA JOSEFINA LOPEZ CARABALLO"},
  {"code": "CEA-065", "name": "STEFFANNIE JULIETH FARFAN GONZALEZ"},
  {"code": "CEA-066", "name": "NUVIA ROSA D'ARTHENAY DE DIAZ"},
  {"code": "CEA-067", "name": "ROSA BERMUDEZ DE BARRIOS"},
  {"code": "CEA-068", "name": "DISTRIBUIDORA YURAIDY 2015. C.A."},
  {"code": "CEA-069", "name": "RAITZA BEATRIZ MALAVE MARIÑA"},
  {"code": "CEA-071", "name": "LUDIS MARIA VARGAS DE GUEDEZ"},
  {"code": "CEA-073", "name": "HILDA ROSA FERMIN PADILLA"},
  {"code": "CEA-074", "name": "DOLORES DE JESUS TORREALBA DE RODRIGUEZ"},
  {"code": "CEA-075", "name": "AMAURY DINI ALENCAR MIRABAL"},
  {"code": "CEA-077", "name": "BEATRIZ COROMOTO MOSQUERA TIMAURE"},
  {"code": "CEA-078", "name": "YELY ELIZABETH GARCIA MUÑOZ"},
  {"code": "CEA-080", "name": "INVERSIONES YOLIMAR ZAMORA. F.P"},
  {"code": "CEA-081", "name": "MARIA BEATRIZ APONTE ALVAREZ"},
  {"code": "CEA-082", "name": "INVERSIONESY SUMINISTROS CLAUDIA CABALLERO. F.P"},
  {"code": "CEA-083", "name": "LUBRICANTES KATHY. C.A."},
  {"code": "CEA-084", "name": "ZENAIDA MARGARITA GRATEROL GARCIA"},
  {"code": "CEA-086", "name": "DISTRIBUIDORA YESLINAY DE HERNAN ALFREDO"},
  {"code": "CEA-087", "name": "FANNY BEATRIZ CALDERAS VALERO"},
  {"code": "CEA-088", "name": "COMERCIALIZADORA MIS PUEBLOS ANDINOS"},
  {"code": "CEA-089", "name": "REPRESENTACIONES GRANACAL. S.R.L"},
  {"code": "CEA-090", "name": "YILDA ARACELIS ORDOÑEZ PEREZ"},
  {"code": "CEA-091", "name": "LETTY MARIA LUGO ARTEAGA"},
  {"code": "CEA-092", "name": "YOLIS ROSALBA CARVAJAL RAMIREZ"},
  {"code": "CEA-093", "name": "YDYEN ISABEL MONGER DE PACHECO"},
  {"code": "CEA-094", "name": "NILDA MARGARITA MESONES"},
  {"code": "CEA-097", "name": "CARMEN MARINA LACROIX DE CORDERO"},
  {"code": "CEA-098", "name": "MARITZA MANRIQUE DE ESCOBAR"},
  {"code": "CEA-100", "name": "ELSY YENIREE ULACIO MONTOYA"},
  {"code": "CEA-101", "name": "ANA XIOMARA AROCHA DE LOPEZ"},
  {"code": "CEA-102", "name": "NELLY JOSEFINA RODRIGUEZ"},
  {"code": "CEA-103", "name": "ANGEL JOSUE CORONEL PEREZ"},
  {"code": "CEA-104", "name": "INVERSIONES DASHITA C.A."},
  {"code": "CEA-105", "name": "JUANA COROMOTO SANDOVAL DE CASTILLO"},
  {"code": "CEA-106", "name": "ALBA ELISA BRAVO BRACHO"},
  {"code": "CEA-107", "name": "ALBA MARINA GUEVARA SALAZAR"},
  {"code": "CEA-108", "name": "MIRIAM DEL VALLE ESQUEDA"},
  {"code": "CEA-109", "name": "NADIA LLYNE HERNANDEZ RODRIGUEZ"},
  {"code": "CEA-110", "name": "YAMILET COROMOTO ARTILES PEÑA"},
  {"code": "CEA-111", "name": "VICTORIA ZOLANO"},
  {"code": "CEA-112", "name": "DABEIBA CUELLAR RUSINQUE"},
  {"code": "CEA-116", "name": "GLADIS DEL CARMEN FALCON"},
  {"code": "CEA-117", "name": "SILVIA YUMILDE JIMENEZ PEÑA"},
  {"code": "CEA-118", "name": "MARIA ELAUTERIA DIAZ TERAN"},
  {"code": "CEA-119", "name": "LISSETH COROMOTO MARAMARA CAMACHO"},
  {"code": "CEA-120", "name": "YUNIOR OSCAR CASTILLO GUTIERREZ"},
  {"code": "CEA-121", "name": "YALILY PAULINA MENDOZA ESPINOZA"},
  {"code": "CEA-122", "name": "NURI COROMOTO GOYO MUJICA"},
  {"code": "CEA-123", "name": "EDECIA COROMOTO PACHECO BALLESTEROS"},
  {"code": "CEA-124", "name": "DEICY YETZENIA PINEDA SANDOVAL"},
  {"code": "CEA-125", "name": "ZAIDA GREGORIA RODRIGUEZ FLORES"},
  {"code": "CEA-127", "name": "INVERSORA DILOJA C.A"},
  {"code": "CEA-129", "name": "AMBAR MARINA LACRUZ HUMBRIA"},
  {"code": "CEA-130", "name": "SANDRA KARINA OSPINA ROPERO"},
  {"code": "CEA-131", "name": "DAMELIS MARIA MEDINA GONZALEZ"},
  {"code": "CEA-132", "name": "YAINE MARLENE SALAS"},
  {"code": "CEA-133", "name": "ALEXI COROMOTO OCANTO DE ALVARADO"},
  {"code": "CEA-134", "name": "NELLY JOSEFINA MORON HERNANDEZ"},
  {"code": "CEA-135", "name": "LISETT YANINE PERNIA HERNANDEZ"},
  {"code": "CEA-137", "name": "MAYIRA COROMOTO ARAUJO PENA"},
  {"code": "CEA-138", "name": "RAUXI MILAGROS IDROGO"},
  {"code": "CEA-139", "name": "YENNY YUSMELY MARTINEZ SANDOVAL"},
  {"code": "CEA-141", "name": "MAVIS DEL VALLE BRITO DE ARCOS"},
  {"code": "CEA-143", "name": "OSMAN JOSE TIRADO"},
  {"code": "CEA-144", "name": "JUDITH JANETH BONIAS BENEGAS"},
  {"code": "CEA-147", "name": "TIBISAY BERENICE GUERRERO MARTINEZ"},
  {"code": "CEA-148", "name": "NORIS MAIGUALIDA NUÑEZ DE MARTINEZ"},
  {"code": "CEA-149", "name": "MISAEL MARIA GUTIERREZ PEREIRA"},
  {"code": "CEA-150", "name": "FLOR MARIA PARRA LUZARDO"},
  {"code": "CEA-151", "name": "MARIA CENELIA ZORA ARDILA"},
  {"code": "CEA-153", "name": "COMERCIALIZADORA ROLGRANCA. C.A"},
  {"code": "CEA-154", "name": "DIOZAIRA MARIA ALCALA ACOSTA"},
  {"code": "CEA-155", "name": "AUDRI CAROLINA SALAS CUEVAS"},
  {"code": "CEA-156", "name": "VIRGINIA DEL VALLE RAMIREZ"},
  {"code": "CEA-157", "name": "\"COPIAS PAPELERIA Y DETALLES \"DIVINA MISERICORDIA\" "},
  {"code": "CEA-158", "name": "CORPORACION CECIMAR C.A."},
  {"code": "CEA-159", "name": "COMERCIAL GELYREI F.P"},
  {"code": "CEA-161", "name": "OLEINI JOSEFINA MARCHAN DE BOLIVAR"},
  {"code": "CEA-162", "name": "DANNELY MORLOY INVERCIONES SAN CARLOS"},
  {"code": "CEA-163", "name": "YARITZA COROMOTO MEJIAS"},
  {"code": "CEA-164", "name": "VARIEDADES Y SERVICIOS LA PATRONA RODRIGUEZ FP"},
  {"code": "CEA-165", "name": "INVERSIONES LVC BETANCOURT 2. F.P."},
  {"code": "CEA-166", "name": "MARLEI MARIA ROMERO ZAMBRANO"},
  {"code": "CEA-170", "name": "LEDY ARELI MARTINEZ"},
  {"code": "CEA-172", "name": "DISTRIBUIDORA VALELUZ"},
  {"code": "CEA-173", "name": "A FLOR DE PIEL"}
];

const RAW_PRODUCTS = [
  {"code": "PT-00001", "name": "PRE-TRATAMIENTO NAT CAYENA 400 cc", "price": 5.0, "value": true, "img": "shampoo.png"},
  {"code": "PT-00002", "name": "POST-TRATAMIENTO NAT CAYENA 400 cc", "price": 5.0, "value": true, "img": "conditioner.png"},
  {"code": "PT-00003", "name": "BAÑO DE CREMA NAT CAYENA 250 g", "price": 4.30, "value": true, "img": "beauty.png"},
  {"code": "PT-00004", "name": "CREMA PEINAR NAT CAYENA 120 cc", "price": 3.20, "value": true, "img": "shower-gel.png"},
  {"code": "PT-00005", "name": "PRE-TRATAMIENTO NAT SABILA 400 cc", "price": 5.0, "value": true, "img": "shampoo.png"},
  {"code": "PT-00006", "name": "POST-TRATAMIENTO NAT SABILA 400 cc", "price": 5.0, "value": true, "img": "conditioner.png"},
  {"code": "PT-00007", "name": "BAÑO CREMA NAT SABILA 250 g", "price": 4.30, "value": true, "img": "beauty.png"},
  {"code": "PT-00008", "name": "CREMA PEINAR NAT SABILA120 cc", "price": 3.20, "value": true, "img": "shower-gel.png"},
  {"code": "PT-00011", "name": "BAÑO CREMA ANTICAIDA 250 g", "price": 4.50, "value": true, "img": "beauty.png"},
  {"code": "PT-00013", "name": "CREMA HUMECTANTE LC BABY 250 cc", "price": 3.90, "value": true, "img": "hand-cream.png"},
  {"code": "PT-00014", "name": "COLONIA LC BABY 250 cc", "price": 3.90, "value": true, "img": "cologne.png"},
  {"code": "PT-00015", "name": "CREMA PAÑALITIS LC BABY 120 g", "price": 4.0, "value": true, "img": "hand-cream.png"},
  {"code": "PT-00017", "name": "CREMA DE MANOS CON SILICONA 120 g", "price": 3.20, "value": true, "img": "hand-cream.png"},
  {"code": "PT-00018", "name": "LOCION PRIMAVERA 250 cm3", "price": 3.70, "value": true, "img": "shampoo.png"},
  {"code": "PT-00020", "name": "LOCION PRIMAVERA MANDARINA 250 cm3", "price": 3.70, "value": true, "img": "shampoo.png"},
  {"code": "PT-00022", "name": "TONICO CAPILAR 120 cc", "price": 3.80, "value": true, "img": "capilar.png"},
  {"code": "PT-00023", "name": "SILICONA COLOR  40 cc", "price": 5.50, "value": true, "img": "capilar.png"},
  {"code": "PT-00025", "name": "GEL ANTI BACTERIAL 130 cc", "price": 3, "value": true, "img": "capilar.png"},
  {"code": "PT-00026", "name": "SHOWER GEL MAGNOLIA 250 cc", "price": 4.50, "value": true, "img": "shower-gel.png"},
  {"code": "PT-00027", "name": "BODY LOTION MAGNOLIA 250 cc", "price": 4.60, "value": true, "img": "shower-gel.png"},
  {"code": "PT-00028", "name": "SPLASH CORPORAL MAGNOLIA 250 cc", "price": 5.70, "value": true, "img": "spray-bottle.png"},
  {"code": "PT-00029", "name": "SHOWER GEL GARDENIA 250 cc", "price": 4.50, "value": true, "img": "shower-gel.png"},
  {"code": "PT-00030", "name": "BODY LOTION GARDENIA 200 cc", "price": 4.60, "value": true, "img": "shower-gel.png"},
  {"code": "PT-00031", "name": "SPLASH CORPORAL GARDENIA 250 cc", "price": 5.70, "value": true, "img": "spray-bottle.png"},
  {"code": "PT-00032", "name": "CREMA PIES RELAX 250 cc", "price": 4.40, "value": true, "img": "hand-cream.png"},
  {"code": "PT-00033", "name": "CREMA EXFOLIADORA RELAX 250 g", "price": 4.50, "value": true, "img": "hand-cream.png"},
  {"code": "PT-00037", "name": "GEL ARNICA DESCONGESTIONANTE 250 cc", "price": 4.70, "value": true, "img": "gel.png"},
  {"code": "PT-00039", "name": "CREMA HIDRATANTE ALOE VERA 100 g", "price": 3.5, "value": true, "img": "hand-cream.png"},
  {"code": "PT-00044", "name": "ARNICA ACEITE CREMOSO 240ML", "price": 4.5, "value": true, "img": "gel.png"},
  {"code": "PT-00055", "name": "COLONIA PARA DAMA EDICION ESPECIAL 30 ML", "price": 5.5, "value": true, "img": "perfume.png"},
  {"code": "PT-00056", "name": "PRE-TRATAMIENTO MIEL CON GERMEN DE TRIGO 400 cc", "price": 5.00, "value": true, "img": "shampoo.png"},
  {"code": "PT-00057", "name": "POST-TRATAMIENTO MIEL CON GERMEN DE TRIGO 400 cc", "price": 5.00, "value": true, "img": "conditioner.png"},
  {"code": "PT-00058", "name": "BAÑO DE CREMA MIEL CON GERMEN DE TRIGO", "price": 4.30, "value": true, "img": "beauty.png"},
  {"code": "PT-00059", "name": "CREMA DE PEINAR MIEL CON GERMEN DE TRIGO", "price": 3.20, "value": true, "img": "shower-gel.png"},
  {"code": "PT-00060", "name": "ANTITRANSPIRANTE DE DAMA BIO ACTIVO 90GR", "price": 2.90, "value": true, "img": "deodorant.png"},
  {"code": "PT-00061", "name": "ANTITRANSPIRANTE CABALLERO BIO ACTIVO 90GR", "price": 2.90, "value": true, "img": "deodorant.png"},
  {"code": "PT-00062", "name": "ANTITRANSPIRANTE TEEN GIRLS 90GR", "price": 2.90, "value": true, "img": "deodorant.png"},
  {"code": "PT-00063", "name": "ANTITRANSPIRANTE TEEN BOYS 90GR", "price": 2.90, "value": true, "img": "deodorant.png"},
  {"code": "PT-00064", "name": "COLONIA TEEN GIRL 55ML", "price": 4.9, "value": true, "img": "cologne.png"},
  {"code": "PT-00065", "name": "COLONIA TEEN BOY 55ML", "price": 4.9, "value": true, "img": "cologne.png"},
  {"code": "PT-00066", "name": "COLONIA DAMA 55 ML CHANNEL NRO 5", "price": 7.9, "value": true, "img": "perfume.png"},
  {"code": "PT-00067", "name": "SOLUCION JABONOSA INTIMA", "price": 3.80, "value": true, "img": "conditioner.png"},
  {"code": "PT-00080", "name": "PRE-TRATAMIENTO ROMERO CON ACEITE  400 gr", "price": 5.00, "value": true, "img": "shampoo.png"},
  {"code": "PT-00081", "name": "POST-TRATAMIENTO ROMERO CON ACEITE 400 gr", "price": 5.00, "value": true, "img": "conditioner.png"},
  {"code": "PT-00082", "name": "BAÑO DE CREMA ROMERO CON ACEITE DE OLIVA", "price": 4.30, "value": true, "img": "beauty.png"},
  {"code": "PT-00083", "name": "CREMA DE PEINAR ROMERO CON ACEITE DE OLIVA", "price": 3.20, "value": true, "img": "shower-gel.png"},
  {"code": "PT-00084", "name": "BAÑO DE ESPUMA PARA BEBES 250 CC", "price": 3.90, "value": true, "img": "spray-bottle.png"},
  {"code": "PT-00085", "name": "PRE-TRATAMIENTO PROTECCION CAIDA 240 CC", "price": 4.40, "value": true, "img": "shampoo.png"},
  {"code": "PT-00086", "name": "POST-TRATAMIENTO PROTECCION CAIDA 240 CC", "price": 4.00, "value": true, "img": "conditioner.png"},
  {"code": "PT-00088", "name": "COLONIA LE MALE 55 ML", "price": 6.5, "value": true, "img": "perfume.png"},
  {"code": "PT-00089", "name": "LOCION CORPORAL PERFUMADA 100 G", "price": 2.9, "value": true, "img": "cream.png"},
  {"code": "PT-00090", "name": "GEL CREMA PIERNAS CANSADAS", "price": 3.40, "value": true, "img": "hand-cream.png"},
  {"code": "PT-00091", "name": "LOCION PARA DESPUES DE AFEITAR LIOR", "price": 2.78, "value": true, "img": "hand-cream.png"},
  {"code": "PT-00094", "name": "COLONIA DAMA CAROLINA HERRERA", "price": 8, "value": true, "img": "perfume.png"},
  {"code": "PT-00096", "name": "PRE-TRATAMIENTO ANTICASPA", "price": 4.40, "value": true, "img": "shampoo.png"},
  {"code": "PT-00098", "name": "COLONIA DE CABALLERO 10ML HOME IN MOTION", "price": 3, "value": true, "img": "cologne.png"},
  {"code": "PT-00099", "name": "COLONIA 212 CAROLINA HERRERA MEN", "price": 5.5, "value": true, "img": "cologne.png"},
  {"code": "PT-00102", "name": "PRE-TRATAMIENTO COCO ALMENDRAS 400 gr", "price": 5.00, "value": true, "img": "shampoo.png"},
  {"code": "PT-00103", "name": "POST-TRATAMIENTO COCO ALMENDRAS 400 gr", "price": 5.00, "value": true, "img": "conditioner.png"},
  {"code": "PT-00104", "name": "BAÑO DE CREMA COCO CON ACEITE DE ALMENDRAS", "price": 4.30, "value": true, "img": "beauty.png"},
  {"code": "PT-00105", "name": "CREMA DE PEINAR COCO CON ACEITE DE ALMENDRAS", "price": 3.20, "value": true, "img": "shower-gel.png"},
  {"code": "PT-00108", "name": "ANTITRANSPIRANTE CLINICAL LIOR", "price": 3.30, "value": true, "img": "styling-cream.png"},
  {"code": "PT-00109", "name": "PRE-TRATAMIENTO CAYENA 240ML", "price": 3.80, "value": true, "img": "shampoo.png"},
  {"code": "PT-00110", "name": "POST-TRATAMIENTO CAYENA 240ML", "price": 3.60, "value": true, "img": "conditioner.png"},
  {"code": "PT-00112", "name": "SPORT ICE(GEL MENTOLADO)", "price": 2.90, "value": true, "img": "hand-cream.png"},
  {"code": "PT-00114", "name": "GEL DE BAÑO MAGNOLIA - COCO", "price": 4.50, "value": true, "img": "shower-gel.png"},
  {"code": "PT-00115", "name": "BODY LOTION MAGNOLIA - COCO", "price": 4.60, "value": true, "img": "shower-gel.png"},
  {"code": "PT-00116", "name": "SPLASH CORPORAL MAGNOLIA - COCO", "price": 5.70, "value": true, "img": "spray-bottle.png"},
  {"code": "PT-00117", "name": "GEL DE BAÑO ROSA GARDENIA", "price": 4.50, "value": true, "img": "shower-gel.png"},
  {"code": "PT-00118", "name": "LOCION CORPORAL ROSA GARDENIA", "price": 4.60, "value": true, "img": "shower-gel.png"},
  {"code": "PT-00119", "name": "SPLASH CORPORAL ROSA GARDENIA", "price": 5.70, "value": true, "img": "spray-bottle.png"},
  {"code": "PT-00120", "name": "ANTITRANSPIRANTE CLINICAL CON ALOE DE VERA", "price": 3.30, "value": true, "img": "styling-cream.png"},
  {"code": "PT-00121", "name": "PRE-TRATAMIENTO COCO ALMENDRAS 240ML", "price": 3.80, "value": true, "img": "shampoo.png"},
  {"code": "PT-00122", "name": "POST-TRATAMIENTO COCO ALMENDRAS 240ML", "price": 3.60, "value": true, "img": "conditioner.png"},
  {"code": "PT-00123", "name": "COLONIA DE DAMA 10ML (CHANNEL NO 5)", "price": 3, "value": true, "img": "cologne.png"},
  {"code": "PT-00126", "name": "BARRA DERMOLIMPIADORA DE TOCADOR (NEUTRO)", "price": 1.5, "value": true, "img": "soap.png"},
  {"code": "PT-00127", "name": "BARRA DERMOLIMPIADORA DE TOCADOR (ALOE VERA)", "price": 1.5, "value": true, "img": "soap.png"},
  {"code": "PT-00128", "name": "COLONIA LE MALE EDICION ESPECIAL 70 ML", "price": 8, "value": true, "img": "perfume.png"},
  {"code": "PT-00129", "name": "BODY LOTION FOR WOMAN 100 GR EN TUBO COLAPSIBLE", "price": 3, "value": true, "img": "shower-gel.png"},
  {"code": "PT-00130", "name": "AFTER SHAVE FOR MEN 100 GR EN TUBO COLAPSIBLE", "price": 2.9, "value": true, "img": "hand-cream.png"},
  {"code": "PT-00131", "name": "PRE TRATAMIENTO NAT SABILA 240 ML", "price": 3.80, "value": true, "img": "shampoo.png"},
  {"code": "PT-00132", "name": "POST-TRATAMIENTO NAT SABILA 240 ML", "price": 3.60, "value": true, "img": "conditioner.png"},
  {"code": "PT-00133", "name": "PRE TRATAMIENTO NAT MIEL 240 ML", "price": 3.80, "value": true, "img": "shampoo.png"},
  {"code": "PT-00134", "name": "POST-TRATAMIENTO NAT MIEL 240 ML", "price": 3.60, "value": true, "img": "conditioner.png"},
  {"code": "PT-00135", "name": "PRE TRATAMIENTO NAT ROMERO 240 ML", "price": 3.80, "value": true, "img": "shampoo.png"},
  {"code": "PT-00136", "name": "POST-TRATAMIENTO NAT  ROMERO 240 ML", "price": 3.60, "value": true, "img": "conditioner.png"},
  {"code": "PT-00137", "name": "EDICION ESPECIAL FOR WOMAN", "price": 7, "value": true, "img": "special.png"},
  {"code": "PT-00138", "name": "EDICION ESPECIAL FOR MAN", "price": 7, "value": true, "img": "special.png"},
  {"code": "PT-00143", "name": "BARRA DE JABON 90 GR CAYENA", "price": 1.5, "value": true, "img": "soap.png"},
  {"code": "PT-00144", "name": "BARRA DE JABON 90 GR SABILA", "price": 1.5, "value": true, "img": "soap.png"},
  {"code": "PT-00145", "name": "PRE TRATAMIENTO ORO LIQUIDO NEW", "price": 4.40, "value": true, "img": "shampoo.png"},
  {"code": "PT-00146", "name": "POST-TRATAMIENTO ORO LIQUIDO NEW", "price": 4.00, "value": true, "img": "conditioner.png"},
  {"code": "PT-00147", "name": "BAÑO DE CREMA ORO LIQUIDO NEW", "price": 4.50, "value": true, "img": "beauty.png"},
  {"code": "PT-00148", "name": "CREMA DE PEINAR ORO LIQUIDO NEW", "price": 3.70, "value": true, "img": "shower-gel.png"},
  {"code": "PT-00149", "name": "MASCARILLA ORO LIQUIDO NEW", "price": 3.40, "value": true, "img": "styling-cream.png"},
  {"code": "PT-00150", "name": "COLONIA CABALLERO VICTORIOUS 55 ML", "price": 6.8, "value": true, "img": "perfume.png"},
  {"code": "PT-00151", "name": "COLONIA CABALLERO BIG PON 10 ML", "price": 3, "value": true, "img": "cologne.png"},
  {"code": "PT-00153", "name": "ESTUCHE DE DAMA EDICION ESPECIAL", "price": 10, "value": true, "img": "special.png"},
  {"code": "PT-00154", "name": "ESTUCHE DE CABALLERO EDICION ESPECIAL", "price": 10, "value": true, "img": "special.png"},
  {"code": "PT-00155", "name": "SPLASH CORPORAL IN LOVE 250ML", "price": 6.8, "value": true, "img": "spray-bottle.png"},
  {"code": "PT-00156", "name": "SPLASH CORPORAL FRAGATTA 250ML", "price": 6.8, "value": true, "img": "spray-bottle.png"},
  {"code": "PT-00158", "name": "SPLASH CORPORAL KHALA 240ML", "price": 5.5, "value": true, "img": "spray-bottle.png"},
  {"code": "PT-00159", "name": "LOCION CORPORAL KHALA 240ML", "price": 4.40, "value": true, "img": "shower-gel.png"}
];

// Data Transformation Helpers

function getInitials(name: string): string {
  const parts = name.split(' ');
  if (parts.length >= 2) {
    return (parts[0][0] + parts[1][0]).toUpperCase();
  }
  return name.slice(0, 2).toUpperCase();
}

function determineCategory(name: string): string {
    const n = name.toUpperCase();
    if (n.includes('SHAMPOO') || n.includes('TRATAMIENTO') || n.includes('BAÑO DE CREMA') || n.includes('CAPILAR') || n.includes('MASCARILLA') || n.includes('ANTICASPA') || n.includes('CREMA DE PEINAR') || n.includes('SILICONA')) return 'Cuidado Capilar';
    if (n.includes('COLONIA') || n.includes('PERFUME') || n.includes('SPLASH')) return 'Perfumería';
    if (n.includes('JABON') || n.includes('SHOWER') || n.includes('BARRA')) return 'Higiene';
    if (n.includes('CREMA') || n.includes('LOCION') || n.includes('GEL') || n.includes('ACEITE') || n.includes('ANTITRANSPIRANTE')) return 'Cuidado Corporal';
    return 'Otros';
}

function extractUnit(name: string): string {
    const match = name.match(/(\d+\s*(?:cc|g|ml|kg|cm3|gr|GR|ML|CC|ML|G))/);
    return match ? match[0] : '';
}

// Exported Constants

export const USERS: User[] = RAW_USERS.map(u => ({
    id: u.code,
    name: u.name,
    role: 'Cliente Registrado',
    avatarInitials: getInitials(u.name),
    email: ''
}));

export const PRODUCTS: Product[] = RAW_PRODUCTS.map(p => ({
    id: p.code,
    name: p.name,
    category: determineCategory(p.name),
    price: p.price,
    unit: extractUnit(p.name) || 'Unidad',
    imageType: p.img
}));

export const CATEGORIES = ['Todos', 'Cuidado Capilar', 'Perfumería', 'Cuidado Corporal', 'Higiene', 'Otros'];

export const RECENT_ORDERS: Order[] = [
    {
        id: '4029',
        customer: 'AROMATICA TUY.',
        amount: 150.00,
        status: 'Completado',
        timeAgo: 'Hace 2h'
    },
    {
        id: '4030',
        customer: 'INVERSIONES CEPORT. C.A.',
        amount: 85.50,
        status: 'Pendiente',
        timeAgo: 'Hace 45m'
    }
];
